name: CI/CD AniQuiz

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  # --- QUALITÉ ET SÉCURITÉ ---
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
      - name: Run Govtulncheck # Vérifie les failles de sécurité connues dans tes deps
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...

  # --- BACKEND ---
  backend-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
      - name: Build
        run: go build -v ./...
      - name: Test with Coverage
        run: go test -v ./... -coverprofile=coverage.out
      # Optionnel : Tu peux afficher le % de couverture ici

  # --- FRONTEND ---
  frontend-ops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build
        run: |
          cd frontend
          npm ci
          npm run build

  # --- DOCKER BUILD CHECK ---
  docker-check:
    runs-on: ubuntu-latest
    needs: [backend-ops, frontend-ops] # Ne se lance que si le reste est OK
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t aniquiz:test .